### ISSUE TITLE
URL이 이상한 것 같습니다.

### ISSUE THREAD

**Issue by Euncheol-Kang** [konantech-ai/deep-learning-framework#1]
https://github.com/konantech-ai/deep-learning-framework#2-생성한-디렉토리로-이동-후-git-clone-명령어를-통해-다운로드

의 내용에 URL이 접근 불가능 합니다.

**Comment by konantech-ai** [comment]
말씀주신 부분 확인 결과, 내부 개발서버 URL로 잘못 등록되어 있는 것이 발견되어 정정하였습니다. 감사합니다.
